#!/bin/bash

###############################################################
# Purpose: Automatically detect uploaded scans, copy them to  #
# Big Kahuna, and begin preprocessing.                        #
# Author: Brianne Sutton, PhD                                 #
# Date: July 2018                                             #
#                                                             #
# To add studies, expand the dirrectory and task dictionaries #
#                                                             #
###############################################################

pswd=`cat /home/brianne/.key`
tmp_mnt='/mnt/threetbrain'
sort_files='/home/brianne/tools/general_utilities/sort_files'
cron_test='no'
debug='no'
dt=`date +"%Y%m%d"`
if [[ "$cron_test" == 'yes' ]] ; then
  echo "cron test done"
else
#Create a dictionary of the directories
declare -A dir_dict
dir_dict=(["Legget_ASDX"]="asdx" ["Legget_EXO"]='exobk' ["Legget_Priming"]='priming' ["Legget_TRN"]='trn' ["Legget_AW"]='awesome' ["Bear_ESES"]='eses')
declare -A task_dict
task_dict=(['asdx']="{'triangle'}" ['exobk']="{'fp_run1' 'fprun2' 'rest' }" ['priming']="{'fp_run1' 'fprun2' 'priming'}" ['trn']="{'triangle'}" ['awesome']="{'oddball' 'fp_run1' 'fp_run2' 'rest'} "['eses']="{'rest'}")

#dir_dict=(["Legget_AW"]='awesome')
#task_dict=(['awesome']="{'oddball' 'fp_run1' 'fp_run2' 'rest'}")

# Convert from dicom to nifti, autodetect ACPC, and start preprocessing
for dk in "${!dir_dict[@]}"; do
  echo ">> Sorting and preprocessing files from: $dk"
  dest=`echo ${dir_dict[$dk]}`
  dest_dir="/data/images/${dest}"
  if [[ -f  ${dest_dir}/subj_to_proc.txt ]] ; then
      readarray -t subjs < ${dest_dir}/subj_to_proc.txt
      subjs=($(printf "%s\n" "${subjs[@]}" | sort -u))
    for s in ${subjs[@]} ; do
      if [[ -e ${dest_dir}/tmp.txt ]] ; then
	  rm ${dest_dir}/tmp.txt
      fi

      if [ -d ${dest_dir}/${s} ] ; then
	  ${sort_files} ${dest} ${s}  # dicom conversion and AC-PC alignment
      else
	  echo "Is the folder for ${s} already renamed?"
	  echo "Use sort_files to proceed"
      fi

      if [[ -e ${dest_dir}/tmp.txt ]] ; then
	  subj=`cat ${dest_dir}/tmp.txt`
	  echo "Searching for: $subj"
	  task_list=`echo ${task_dict[$dest]}`
          subj=`echo "'$subj'"`
#          cd ${dest_dir} # The file selector script needs to be close to the correct starting spot (e.g., /data/images, not /home/korey)
#          matlab -nosplash -nodesktop -r "in_set = containers.Map({'art'},[1]); addpath('/usr/local/MATLAB/tools/fmri_processing_utilities'); preproc_fmri($subj,$task_list,in_set); quit"
      fi
    done
  fi
done
fi
exit
